import './style.css';
import { AreaSeries, BarSeries, CandlestickSeries, ColorType, HistogramSeries, LineSeries, createChart } from 'lightweight-charts';
import { api, type Bar, type SymbolInfo } from './api';
import { bollinger, ema, macd, rsi, sma, type Indicator } from './indicators';

type Preferences = { symbol: string; interval: string; chartType: string; theme: 'dark' | 'light'; indicators: Indicator[]; session: string };
const stored = JSON.parse(localStorage.getItem('stock-dashboard') || '{}') as Partial<Preferences>;
const state: Preferences = { symbol: stored.symbol || 'SPY', interval: stored.interval || '1d', chartType: stored.chartType || 'candle', theme: stored.theme || 'dark', indicators: stored.indicators || [{ id: 'volume', kind: 'volume' }], session: stored.session || 'regular' };
const colors = ['#2962ff', '#ff6d00', '#ab47bc', '#00bfa5', '#ef5350', '#8d6e63'];
let chart: any; let priceSeries: any; let indicatorSeries: any[] = []; let bars: Bar[] = []; let versions = new Map<string, string>(); let symbolList: SymbolInfo[] = []; let followLatest = true;
const el = (id: string) => document.getElementById(id)!;
const save = () => localStorage.setItem('stock-dashboard', JSON.stringify(state));
const toast = (message: string) => { const node = el('toast'); node.textContent = message; node.classList.remove('hidden'); setTimeout(() => node.classList.add('hidden'), 3500); };

function chartOptions() {
  const dark = state.theme === 'dark'; return { layout: { background: { type: ColorType.Solid, color: dark ? '#121722' : '#ffffff' }, textColor: dark ? '#d1d4dc' : '#191c22' }, grid: { vertLines: { color: dark ? '#1f2937' : '#e7e9ee' }, horzLines: { color: dark ? '#1f2937' : '#e7e9ee' } }, crosshair: { mode: 1 }, rightPriceScale: { borderColor: dark ? '#303845' : '#c7ccd5' }, timeScale: { borderColor: dark ? '#303845' : '#c7ccd5', timeVisible: true, secondsVisible: false } };
}
function makeChart() {
  if (chart) chart.remove();
  const node = el('chart'); chart = createChart(node, { ...chartOptions(), width: node.clientWidth, height: node.clientHeight });
  new ResizeObserver(() => chart.applyOptions({ width: node.clientWidth, height: node.clientHeight })).observe(node);
  chart.timeScale().subscribeVisibleLogicalRangeChange((range: any) => { followLatest = !range || range.to >= bars.length - 3; });
  createPriceSeries(); renderData(true);
}
function createPriceSeries() {
  if (state.chartType === 'candle') priceSeries = chart.addSeries(CandlestickSeries, { upColor: '#26a69a', downColor: '#ef5350', borderVisible: false, wickUpColor: '#26a69a', wickDownColor: '#ef5350' });
  else if (state.chartType === 'bar') priceSeries = chart.addSeries(BarSeries, { upColor: '#26a69a', downColor: '#ef5350' });
  else if (state.chartType === 'area') priceSeries = chart.addSeries(AreaSeries, { lineColor: '#2962ff', topColor: 'rgba(41,98,255,.42)', bottomColor: 'rgba(41,98,255,.03)', lineWidth: 2 });
  else priceSeries = chart.addSeries(LineSeries, { color: '#2962ff', lineWidth: 2 });
}
function priceData() { return state.chartType === 'line' || state.chartType === 'area' ? bars.map((b) => ({ time: b.time, value: b.close })) : bars; }
function renderIndicators() {
  indicatorSeries.forEach((series) => chart.removeSeries(series)); indicatorSeries = []; const legend: string[] = [];
  state.indicators.forEach((indicator, index) => { const color = colors[index % colors.length];
    if (indicator.kind === 'sma' || indicator.kind === 'ema') { const data = indicator.kind === 'sma' ? sma(bars, indicator.period) : ema(bars, indicator.period); const series = chart.addSeries(LineSeries, { color, lineWidth: 2, title: `${indicator.kind.toUpperCase()} ${indicator.period}` }); series.setData(data); indicatorSeries.push(series); legend.push(`${indicator.kind.toUpperCase()}(${indicator.period})`); }
    if (indicator.kind === 'bb') { const data = bollinger(bars, indicator.period, indicator.multiplier); [data.middle, data.upper, data.lower].forEach((line, i) => { const series = chart.addSeries(LineSeries, { color: i === 0 ? color : `${color}99`, lineWidth: 1, title: i === 0 ? `BB ${indicator.period}` : '' }); series.setData(line); indicatorSeries.push(series); }); legend.push(`BB(${indicator.period}, ${indicator.multiplier})`); }
    if (indicator.kind === 'volume') { const series = chart.addSeries(HistogramSeries, { priceFormat: { type: 'volume' }, priceScaleId: 'vol', color: '#26a69a' }, 1); series.setData(bars.map((b) => ({ time: b.time, value: b.volume, color: b.close >= b.open ? '#26a69a99' : '#ef535099' }))); indicatorSeries.push(series); chart.priceScale('vol').applyOptions({ scaleMargins: { top: 0.75, bottom: 0 } }); legend.push('Volume'); }
    if (indicator.kind === 'rsi') { const series = chart.addSeries(LineSeries, { color, title: `RSI ${indicator.period}` }, 2); series.setData(rsi(bars, indicator.period)); series.createPriceLine({ price: 70, color: '#ef535099', lineStyle: 2, lineWidth: 1, axisLabelVisible: true, title: '70' }); series.createPriceLine({ price: 30, color: '#26a69a99', lineStyle: 2, lineWidth: 1, axisLabelVisible: true, title: '30' }); indicatorSeries.push(series); legend.push(`RSI(${indicator.period})`); }
    if (indicator.kind === 'macd') { const data = macd(bars, indicator.fast, indicator.slow, indicator.signal); const line = chart.addSeries(LineSeries, { color: '#2962ff', title: 'MACD' }, 3); const signal = chart.addSeries(LineSeries, { color: '#ff6d00', title: 'Signal' }, 3); const hist = chart.addSeries(HistogramSeries, { color: '#26a69a' }, 3); line.setData(data.line); signal.setData(data.signal); hist.setData(data.histogram.map((p) => ({ ...p, color: p.value >= 0 ? '#26a69a' : '#ef5350' }))); indicatorSeries.push(line, signal, hist); legend.push('MACD(12,26,9)'); }
  });
  el('legend').innerHTML = legend.map((name, i) => `<button class="chip" data-remove="${state.indicators[i]?.id || ''}">${name} ×</button>`).join('');
  document.querySelectorAll<HTMLButtonElement>('[data-remove]').forEach((button) => button.onclick = () => { state.indicators = state.indicators.filter((item) => item.id !== button.dataset.remove); save(); makeChart(); });
}
function renderData(reset = false) {
  priceSeries.setData(priceData()); renderIndicators(); if (reset) chart.timeScale().fitContent(); updateQuote();
}
function updateQuote() { const bar = bars.at(-1); if (!bar) { el('quote').textContent = `${state.symbol} 暂无数据`; return; } const previous = bars.at(-2)?.close || bar.close; const delta = bar.close - previous; el('quote').textContent = `${state.symbol}  ${bar.close.toFixed(2)}  ${delta >= 0 ? '+' : ''}${delta.toFixed(2)} (${(delta / previous * 100).toFixed(2)}%)`; }
async function loadChart(reset = true) { try { const response = await api.chart(state.symbol, state.interval, state.session); bars = response.bars; versions.set(state.symbol, response.data_version); renderData(reset); el('status').textContent = `${response.source_table} · ${response.bars.length} 根 · UTC`; } catch (error) { toast((error as Error).message); } }
async function refreshLatest() { const current = bars.at(-1); if (!current) return loadChart(true); try { const response = await api.chart(state.symbol, state.interval, state.session, current.time - 600); if (!response.bars.length) return; const known = new Map(bars.map((bar) => [bar.time, bar])); response.bars.forEach((bar) => known.set(bar.time, bar)); bars = [...known.values()].sort((a, b) => a.time - b.time); response.bars.forEach((bar) => priceSeries.update(state.chartType === 'line' || state.chartType === 'area' ? { time: bar.time, value: bar.close } : bar)); versions.set(state.symbol, response.data_version); renderIndicators(); updateQuote(); if (followLatest) chart.timeScale().scrollToRealTime(); } catch { /* retain visible chart on transient refresh error */ } }
function intervalButtons() { const choices: [string, string][] = [['5m', '5m'], ['30m', '30m'], ['1h', '1h'], ['2h', '2h'], ['4h', '4h'], ['1d', '1D'], ['1wk', '1W'], ['1mo', '1M'], ['1y', '1Y']]; el('intervals').innerHTML = choices.map(([value, label]) => `<button data-interval="${value}" class="${state.interval === value ? 'active' : ''}">${label}</button>`).join(''); document.querySelectorAll<HTMLButtonElement>('[data-interval]').forEach((button) => button.onclick = () => { state.interval = button.dataset.interval!; save(); intervalButtons(); loadChart(true); }); }
function renderSymbols() { const select = el('symbol-select') as HTMLSelectElement; select.innerHTML = symbolList.map((info) => `<option value="${info.yahoo_symbol}">${info.symbol}</option>`).join(''); if (!symbolList.some((item) => item.yahoo_symbol === state.symbol)) state.symbol = symbolList[0]?.yahoo_symbol || 'SPY'; select.value = state.symbol; el('symbols').innerHTML = symbolList.map((info) => `<div class="symbol-entry"><button class="symbol-row ${info.yahoo_symbol === state.symbol ? 'selected' : ''}" data-symbol="${info.yahoo_symbol}"><b>${info.symbol}</b><span>${info.task.status === 'ready' ? '已就绪' : info.task.status}</span><small>${info.daily_rows} D · ${info.intraday_rows} 5m</small>${info.last_error ? '<i>下载失败</i>' : ''}</button>${info.last_error ? `<button class="retry" data-retry="${info.yahoo_symbol}">重试</button>` : ''}</div>`).join(''); document.querySelectorAll<HTMLButtonElement>('[data-symbol]').forEach((button) => button.onclick = async () => { state.symbol = button.dataset.symbol!; save(); renderSymbols(); await loadChart(true); }); document.querySelectorAll<HTMLButtonElement>('[data-retry]').forEach((button) => button.onclick = async () => { try { await api.refresh(button.dataset.retry!); toast('已加入刷新队列'); await loadSymbols(); } catch (error) { toast((error as Error).message); } }); }
async function loadSymbols() { try { const response = await api.symbols(); symbolList = response.symbols; (el('session-control')).classList.toggle('hidden', !response.has_extended_hours); renderSymbols(); } catch (error) { toast((error as Error).message); } }
function indicatorMenu() { const menu = el('indicator-menu'); menu.innerHTML = `<button data-kind="sma">SMA…</button><button data-kind="ema">EMA…</button><button data-kind="bb">Bollinger Bands…</button><hr><button data-kind="volume">Volume</button><button data-kind="rsi">RSI…</button><button data-kind="macd">MACD</button>`; menu.querySelectorAll<HTMLButtonElement>('button').forEach((button) => button.onclick = () => { const kind = button.dataset.kind!; const period = Number(prompt('周期', kind === 'bb' ? '20' : kind === 'rsi' ? '14' : '20')) || 20; const id = `${kind}-${Date.now()}`; const item: Indicator = kind === 'volume' ? { id, kind: 'volume' } : kind === 'bb' ? { id, kind: 'bb', period, multiplier: 2 } : kind === 'rsi' ? { id, kind: 'rsi', period } : kind === 'macd' ? { id, kind: 'macd', fast: 12, slow: 26, signal: 9 } : { id, kind: kind as 'sma' | 'ema', period }; state.indicators.push(item); save(); menu.classList.add('hidden'); makeChart(); }); }
function bind() { intervalButtons(); indicatorMenu(); (el('symbol-select') as HTMLSelectElement).onchange = (event) => { state.symbol = (event.target as HTMLSelectElement).value; save(); renderSymbols(); loadChart(true); }; (el('symbol-search') as HTMLInputElement).oninput = (event) => { const query = (event.target as HTMLInputElement).value.trim().toUpperCase(); document.querySelectorAll<HTMLElement>('.symbol-entry').forEach((row) => row.classList.toggle('hidden', Boolean(query) && !row.textContent!.toUpperCase().includes(query))); }; (el('chart-type') as HTMLSelectElement).value = state.chartType; (el('chart-type') as HTMLSelectElement).onchange = (event) => { state.chartType = (event.target as HTMLSelectElement).value; save(); makeChart(); }; el('fit').onclick = () => chart.timeScale().fitContent(); el('latest').onclick = () => { followLatest = true; chart.timeScale().scrollToRealTime(); }; el('theme').onclick = () => { state.theme = state.theme === 'dark' ? 'light' : 'dark'; document.documentElement.dataset.theme = state.theme; save(); makeChart(); }; el('indicators').onclick = () => el('indicator-menu').classList.toggle('hidden'); (el('session-toggle') as HTMLInputElement).onchange = (event) => { state.session = (event.target as HTMLInputElement).checked ? 'extended' : 'regular'; save(); loadChart(true); }; el('add-symbol').onclick = async () => { const value = prompt('输入代码，可用逗号、空格或换行分隔，例如 AAPL, BRK.B'); if (!value) return; try { await api.add(value); toast('已加入队列，正在回填数据'); await loadSymbols(); } catch (error) { toast((error as Error).message); } }; }
async function start() { document.documentElement.dataset.theme = state.theme; bind(); makeChart(); await loadSymbols(); await loadChart(true); setInterval(async () => { const previous = versions.get(state.symbol); await loadSymbols(); if (versions.get(state.symbol) === previous) await refreshLatest(); }, 30000); }
void start();
